### ISSUE TITLE
Contextual Swashes example

### ISSUE THREAD

**Issue by ffoodd** [sparanoid/opentype-features#1]
Hi there,

This webpage is awesome, thanks a lot for those examples :)

May I suggest the Bello Pro font for (at least) contextual swashes?

* [Bello Pro on Typekit](https://typekit.com/fonts/bello)
* [Bello Pro features on Underware](http://www.underware.nl/fonts/bello/features/how_does_it_work/)

It has many OpenType featuresthat could help fill in missing examples.

Keep going!

**Comment by sparanoid** [comment]
Great font (pun intended)!
