### ISSUE TITLE
Doesn't respect chrome zoom

### ISSUE THREAD

**Issue by StanLindsey** [sparanoid/opentype-features#3]
The text is massive on my monitor. 

Instinctively I hit `CMD`+`-`. 

Zooming has no effect. 
I literally had to move my chair back so I comfortably view the site.

**Comment by sparanoid** [comment]
What browser are you using? and your screen resolution?

This project uses [viewport units](https://caniuse.com/#search=viewport%20units) which causes zooming OUT a little bit weird than normal.
